# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
	config.vm.define :node1 do |node_1|
		node_1.vm.box = "base"
		node_1.vm.network :hostonly, "10.0.1.3", :netmask => "255.0.0.0"
		node_1.vm.customize ["modifyvm", :id, "--name", "master-2"]
	end
	config.vm.define :node2 do |node_2|
		node_2.vm.box = "base"
		node_2.vm.network :hostonly, "10.0.1.4", :netmask => "255.0.0.0"
		node_2.vm.customize ["modifyvm", :id, "--name", "slave01"]
	end
	config.vm.define :node3 do |node_3|
		node_3.vm.box = "base"
		node_3.vm.network :hostonly, "10.0.1.5", :netmask => "255.0.0.0"
		node_3.vm.customize ["modifyvm", :id, "--name", "slave02"]
	end
end
