Vagrant::Config.run do |config|
	config.vm.define :node1 do |node_1|
		node_1.vm.box = "precise64"
		node_1.vm.network :hostonly, "172.18.0.2", :netmask => "255.255.0.0"
		node_1.vm.network :bridged, "eth0"
		node_1.vm.customize ["modifyvm", :id, "--memory", 512, "--name", "condor-master", "--cpus", 2]
		node_1.vm.provision :chef_solo do |chef|
			chef.cookbooks_path = "cookbooks"
			chef.add_recipe "test::users"
			chef.json.merge!({
				:run_list => [ "recipe[test::users]", "recipe[test::java-64]", "recipe[test::installingmaster]" ],
				:host_name => "master.cluster.org",
			})
		end
	end
	config.vm.define :node2 do |node_2|
		node_2.vm.box = "precise64"
		node_2.vm.network :hostonly, "172.18.0.3", :netmask => "255.255.0.0"
		node_2.vm.customize ["modifyvm", :id, "--memory", 896, "--name", "workernode1", "--cpus", 2]
		node_2.vm.provision :chef_solo do |chef|
			chef.cookbooks_path = "cookbooks"
			chef.add_recipe "test::users"
			chef.json.merge!({
				:run_list => [ "recipe[test::users]", "recipe[test::java-64]", "recipe[test::installingwn]" ],
				:host_name => "wn1.cluster.org",
			})
		end
	end
	config.vm.define :node3 do |node_3|
		node_3.vm.box = "precise64"
		node_3.vm.network :hostonly, "172.18.0.4", :netmask => "255.255.0.0"
		node_3.vm.customize ["modifyvm", :id, "--memory", 896, "--name", "workernode2", "--cpus", 2]
		node_3.vm.provision :chef_solo do |chef|
			chef.cookbooks_path = "cookbooks"
			chef.add_recipe "test::users"
			chef.json.merge!({
				:run_list => [ "recipe[test::users]", "recipe[test::java-64]", "recipe[test::installingwn]" ],
				:host_name => "wn2.cluster.org",
			})
		end
	end
	config.vm.define :node4 do |node_4|
		node_4.vm.box = "precise64"
		node_4.vm.network :hostonly, "172.18.0.5", :netmask => "255.255.0.0"
		node_4.vm.customize ["modifyvm", :id, "--memory", 896, "--name", "workernode3", "--cpus", 2]
		node_4.vm.provision :chef_solo do |chef|
			chef.cookbooks_path = "cookbooks"
			chef.add_recipe "test::users"
			chef.json.merge!({
				:run_list => [ "recipe[test::users]", "recipe[test::java-64]", "recipe[test::installingwn]" ],
				:host_name => "wn3.cluster.org",
			})
		end
	end
end
